# Custom Language File for Launcher Customizer

[ejs.app]
title = "블랙의 놀이터"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/KimblackPlayground"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.com/invite/R4mWMuSyhh"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/KimblackPlayground"
supportLink = "https://github.com/CustomLauncherLab/KimblackPlayground/issues"

[ejs.welcome]
welcomeHeader = "블랙의 놀이터"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."
