name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          PFX_DOWNLOAD_URL: ${{ secrets.PFX_DOWNLOAD_URL }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -o ./gotiger.pfx $PFX_DOWNLOAD_URL
          export CSC_LINK=./gotiger.pfx
          export CSC_KEY_PASSWORD=$CSC_KEY_PASSWORD
          npm run dist
        shell: bash
